framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            neuromancer:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%&queue_name=neuromancer'
                options:
                    use_notify: false # would probably be more efficient if we could use LISTEN/NOTIFY, but did not work for me, so disabling.
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            wintermute:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%&queue_name=wintermute'
                options:
                    use_notify: false
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\Message\NeuromancerMessage: neuromancer
            App\Message\WintermuteMessage: wintermute
